<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FileHandler-021d2d44-f4b7-440b-a478-369c01f391e4</UserSecretsId>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HelperFiles\model.onnx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="HelperFiles\model.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Comuns\Comuns.csproj" />
    <ProjectReference Include="..\CustomVisionPredictionService\CustomVisionPredictionService.csproj" />
    <ProjectReference Include="..\YoloPredictionService\YoloPredictionService.csproj" />
  </ItemGroup>
</Project>
